### ISSUE TITLE
Different expression matrix types (for example:rnaseq and affy) crashes rownormalization

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#116]
If you construct a 2 dataset map with two different types of data (for example rnaseq and affy) when you try and row normalize the expresison in the expression viewer you get the following stack:
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Color parameter outside of expected range: Green
    at java.awt.Color.testColorValueRange(Color.java:344)
    at java.awt.Color.<init>(Color.java:462)
    at org.baderlab.csplugins.enrichmentmap.view.HeatMapPanel.getColor(HeatMapPanel.java:608)
    at org.baderlab.csplugins.enrichmentmap.view.HeatMapPanel.createSortedMergedTableData(HeatMapPanel.java:658)
    at org.baderlab.csplugins.enrichmentmap.view.HeatMapPanel.updatePanel(HeatMapPanel.java:376)
    at org.baderlab.csplugins.enrichmentmap.heatmap.HeatMapActionListener.actionPerformed(HeatMapActionListener.java:261)
    at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1260)
    at javax.swing.JComboBox.setSelectedItem(JComboBox.java:588)
    at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:624)
    at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:835)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)

Row normalization should maybe specific to the dataset?  Or maybe have the option to do it globally or by the dataset.

**Comment by risserlin** [comment]
doesn't happen for all genesets.  Only some.  Not sure why. Maybe the row norm range is calculated for dataset 1 and if a gene in dataset is outside the range it crashes.

**Comment by risserlin** [comment]
fixed in 7118d00e93b5f451145fc261ab386d2663534187
