### ISSUE TITLE
AUTO_ANNOTATE build 535 a few observations and bug reports 

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#125]
AUTO-ANNOTATE
a few observations and bug report (sorry for the lack of precision in reporting these issues, I could try to explain or test more to clarify, let me know)
I tried built 535 of EM on Cytoscape 3.2.1
- FONT: 
  - BUG: automatic labelling: the labels are difficult to read: black letters with white borders?
  - ENHANCEMENT: font of automatic labels? lots of space between letters. is it the optimal font? 
  - ENHANCEMENT: be able to get labels on 2 lines if necessary (right click edit : able to reduce the text box length)
  -  I finally finished the figure using Adobe Illustrator to: change the font to Arial, optimize the label positions, and reduce long labels on 2,3 lines (width of th cluster)
- BUG: extract  and merge options: it did not work properly, I got wrong labelling of clusters
- BUG: move around annotated clusters  because 2 clusters are overlapping for example: sometimes works and sometimes does not ( select nodes of a cluster, move them around and then do 'update' to move the annotation ellipse+label): 'error while drawing bounding circle/box around clusters'
- BUG: when I select a few nodes, it selects retangle(ellipse)/labels elsewhere on the map as well. 
- BUG: I tried to select many nodes (~100, 1 part of the map) and move them left and then clicked on update: got error message (error while drawing bounding circle/box around clusters ...) but could close the error messages each time and at the end only 1 rectangle did not move
  error is : HashMap 894 (see below)
- ENHANCEMENT: include cluster size = 1 (single node) in the automatic labelling so we don't have to relabel them manually when gene-set label is set to "empty"
- ENHANCEMENT: would be nice to see list of clusters on stored session and be able to use the options as well in the stored session
- ENHANCEMENT: would it be possible to have a manual option to create labels: to select some nodes and right click to create an annotated cluster? (manual cluster annotation) (with the use of clusterMaker)
- TESTS AND ERROR MESSAGES
- T1: changing: Ellipse to Rectangle
  Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
  at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
  at java.util.HashMap$KeyIterator.next(HashMap.java:928)
  at org.cytoscape.ding.impl.cyannotator.CyAnnotator.updateNetworkAttributes(CyAnnotator.java:357)
  at org.cytoscape.ding.impl.cyannotator.CyAnnotator.removeAnnotation(CyAnnotator.java:280)
  at org.cytoscape.ding.impl.cyannotator.annotations.AbstractAnnotation.removeAnnotation(AbstractAnnotation.java:322)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.model.Cluster.eraseEllipse(Cluster.java:266)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.view.DisplayOptionsPanel$8.itemStateChanged(DisplayOptionsPanel.java:296)
  at javax.swing.AbstractButton.fireItemStateChanged(AbstractButton.java:2046)
  at javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2348)
  at javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:455)
  at javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:272)
  at javax.swing.ButtonGroup.setSelected(ButtonGroup.java:162)
  at javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:254)
  at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:289)
  at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
  at java.awt.Component.processMouseEvent(Component.java:6505)
  at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
  at java.awt.Component.processEvent(Component.java:6270)
  at java.awt.Container.processEvent(Container.java:2229)
  at java.awt.Component.dispatchEventImpl(Component.java:4861)
  at java.awt.Container.dispatchEventImpl(Container.java:2287)
  at java.awt.Component.dispatchEvent(Component.java:4687)
  at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
  at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
  at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
  at java.awt.Container.dispatchEventImpl(Container.java:2273)
  at java.awt.Window.dispatchEventImpl(Window.java:2719)
  at java.awt.Component.dispatchEvent(Component.java:4687)
  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
  at java.awt.EventQueue.access$200(EventQueue.java:103)
  at java.awt.EventQueue$3.run(EventQueue.java:694)
  at java.awt.EventQueue$3.run(EventQueue.java:692)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
  at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
  at java.awt.EventQueue$4.run(EventQueue.java:708)
  at java.awt.EventQueue$4.run(EventQueue.java:706)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
  at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
  at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
- T2: merge: select 1 cluster in the list + 3 nodes on the map -> message is "you need to select 2 clusters" and then go to "Cytoscape Task --> cancelling (need to stop cytoscape) but no message from the c onsole
- T4: merge: not able to find right combination of keystrokes to select cluters on the list
  
  *T5: merge: ordered list of cluster alphabetically and select 2 adjectent clusters (DNA repair) and clicked on merge: error 101:
  Java.lang.ArrayIndexOutOfBoundsException: 101
  at javax.swing.DefaultRowSorter.setModelToViewFromViewToModel(DefaultRowSorter.java:734)
  at javax.swing.DefaultRowSorter.rowsInserted0(DefaultRowSorter.java:1063)
  at javax.swing.DefaultRowSorter.rowsInserted(DefaultRowSorter.java:868)
  at javax.swing.JTable.notifySorter(JTable.java:4269)
  at javax.swing.JTable.sortedTableChanged(JTable.java:4117)
  at javax.swing.JTable.tableChanged(JTable.java:4394)
  at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.model.ClusterTableModel.addRow(ClusterTableModel.java:123)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.model.ClusterTableModel.addClusterToTable(ClusterTableModel.java:70)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.MergeClustersTask.mergeAction(MergeClustersTask.java:121)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.MergeClustersTask.run(MergeClustersTask.java:138)
  at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
  at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
  at java.util.concurrent.FutureTask.run(FutureTask.java:166)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
- T6:  close the error message 101 from T5; 3 other clusters unrelated to DNA repair were now selected on the list, unable to unselect them, had to close Cytoscape :
  Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 100
  at java.util.Vector.get(Vector.java:744)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.model.ClusterTableModel.getValueAt(ClusterTableModel.java:153)
  at javax.swing.JTable.getValueAt(JTable.java:2716)
  at javax.swing.JTable.prepareRenderer(JTable.java:5714)
  at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114)
  at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016)
  at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812)
  at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
  at javax.swing.JComponent.paintComponent(JComponent.java:778)
  at javax.swing.JComponent.paint(JComponent.java:1054)
  at javax.swing.JComponent.paintToOffscreen(JComponent.java:5221)
  at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1508)
  at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1439)
  at javax.swing.RepaintManager.paint(RepaintManager.java:1236)
  at javax.swing.JComponent.paintForceDoubleBuffered(JComponent.java:1090)
  at javax.swing.JViewport.blitDoubleBuffered(JViewport.java:1598)
  at javax.swing.JViewport.windowBlitPaint(JViewport.java:1559)
  at javax.swing.JViewport.setViewPosition(JViewport.java:1102)
  at javax.swing.plaf.basic.BasicScrollPaneUI$Handler.vsbStateChanged(BasicScrollPaneUI.java:1054)
  at javax.swing.plaf.basic.BasicScrollPaneUI$Handler.stateChanged(BasicScrollPaneUI.java:1043)
  at javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:364)
  at javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:302)
  at javax.swing.DefaultBoundedRangeModel.setValue(DefaultBoundedRangeModel.java:168)
  at javax.swing.JScrollBar.setValue(JScrollBar.java:463)
  at com.apple.laf.AquaScrollBarUI$TrackListener.moveToMouse(AquaScrollBarUI.java:496)
  at com.apple.laf.AquaScrollBarUI$TrackListener.mouseDraggedInTrack(AquaScrollBarUI.java:483)
  at com.apple.laf.AquaScrollBarUI$TrackListener.mouseDragged(AquaScrollBarUI.java:303)
  at java.awt.Component.processMouseMotionEvent(Component.java:6553)
  at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3339)
  at java.awt.Component.processEvent(Component.java:6274)
  at java.awt.Container.processEvent(Container.java:2229)
  at java.awt.Component.dispatchEventImpl(Component.java:4861)
  at java.awt.Container.dispatchEventImpl(Container.java:2287)
  at java.awt.Component.dispatchEvent(Component.java:4687)
  at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
  at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4509)
  at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
  at java.awt.Container.dispatchEventImpl(Container.java:2273)
  at java.awt.Window.dispatchEventImpl(Window.java:2719)
  at java.awt.Component.dispatchEvent(Component.java:4687)
  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
  at java.awt.EventQueue.access$200(EventQueue.java:103)
  at java.awt.EventQueue$3.run(EventQueue.java:694)
  at java.awt.EventQueue$3.run(EventQueue.java:692)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
  at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
  at java.awt.EventQueue$4.run(EventQueue.java:708)
  at java.awt.EventQueue$4.run(EventQueue.java:706)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
  at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
  at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
  
  at java.lang.Thread.run(Thread.java:724)
- T7: selecting nodes on the map with cluster labels selected also the cluster rectangles: able to unselect the nodes but not able to unselect the rectangles
- T8: moved about 3 cluster (~20node) and then clicked on update: and then got an error: Updata cluster label Drowaing cluster Text Label. I was able to close the error message and it was working well after that, the update was made despite the error
  java.util.ConcurrentModificationException
  at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
  at java.util.HashMap$KeyIterator.next(HashMap.java:928)
  at org.cytoscape.ding.impl.cyannotator.CyAnnotator.updateNetworkAttributes(CyAnnotator.java:357)
  at org.cytoscape.ding.impl.cyannotator.CyAnnotator.addAnnotation(CyAnnotator.java:275)
  at org.cytoscape.ding.impl.cyannotator.annotations.AbstractAnnotation.updateAnnotationAttributes(AbstractAnnotation.java:434)
  at org.cytoscape.ding.impl.cyannotator.annotations.AbstractAnnotation.update(AbstractAnnotation.java:387)
  at org.cytoscape.ding.impl.cyannotator.create.TextAnnotationFactory.createAnnotation(TextAnnotationFactory.java:55)
  at org.cytoscape.ding.impl.cyannotator.create.TextAnnotationFactory.createAnnotation(TextAnnotationFactory.java:41)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.DrawClusterLabelTask.drawTextLabel(DrawClusterLabelTask.java:83)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.DrawClusterLabelTask.run(DrawClusterLabelTask.java:102)
  at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337)
  at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
  at java.util.concurrent.FutureTask.run(FutureTask.java:166)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:724)
- T9:when selecting nodes on the map, unrelated label_rectangle box were also selected, needed to "update" several times to get rid of the selection. Globally worked (except for 1 rectangle which stayed in yellow); 1 error message poped up
  2015-09-28 11:23:04.143 java[43440:8694368] plugin com.google.GoogleDrive.FinderSyncAPIExtension interrupted
  java.lang.NullPointerException
  at org.cytoscape.ding.impl.DGraphView.getNodeView(DGraphView.java:2658)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.model.Cluster.updateCoordinates(Cluster.java:190)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.model.AnnotationSet.updateCoordinates(AnnotationSet.java:123)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.SelectClusterTask.deselectCluster(SelectClusterTask.java:58)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.SelectClusterTask.deselectCluster_nonodes(SelectClusterTask.java:156)
  at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.SelectClusterTask.run(SelectClusterTask.java:172)
  at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
  at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
  at java.util.concurrent.FutureTask.run(FutureTask.java:166)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:724)
  2

**Comment by risserlin** [comment]
Added inidividual tickets:
enhancement 1 - (font control) issue #132 
enhancement 2 - (cluster size 1) issue #127 
enhancement 3 - available on seesion restore - should work. 
enhancement 4 - you can do this manually using annotations in cytoscape or you can select nodes and click on extract to have EM do it automatically for you. 

T1 -> issue #131 
T2 + T4 -> issue #128 
T5 + T6 (also related to this are error T7 and T9) -> issue #129 
T8 -> issue #130
