### ISSUE TITLE
Changing the order of the cluster labels - sort alphabetically causes incorrect cluster selection

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#129]
After changing to an alphabetical order on the cluster chart and select 3 clusters erlated to DNA repair -  3 other clusters unrelated to DNA repair were now selected on the list, unable to unselect them, had to close Cytoscape :
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 100
at java.util.Vector.get(Vector.java:744)
at org.baderlab.csplugins.enrichmentmap.autoannotate.model.ClusterTableModel.getValueAt(ClusterTableModel.java:153)
at javax.swing.JTable.getValueAt(JTable.java:2716)
at javax.swing.JTable.prepareRenderer(JTable.java:5714)
at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114)
at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016)
at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812)
at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
at javax.swing.JComponent.paintComponent(JComponent.java:778)
at javax.swing.JComponent.paint(JComponent.java:1054)
at javax.swing.JComponent.paintToOffscreen(JComponent.java:5221)
at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1508)
at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1439)
at javax.swing.RepaintManager.paint(RepaintManager.java:1236)
at javax.swing.JComponent.paintForceDoubleBuffered(JComponent.java:1090)
at javax.swing.JViewport.blitDoubleBuffered(JViewport.java:1598)
at javax.swing.JViewport.windowBlitPaint(JViewport.java:1559)
at javax.swing.JViewport.setViewPosition(JViewport.java:1102)
at javax.swing.plaf.basic.BasicScrollPaneUI$Handler.vsbStateChanged(BasicScrollPaneUI.java:1054)
at javax.swing.plaf.basic.BasicScrollPaneUI$Handler.stateChanged(BasicScrollPaneUI.java:1043)
at javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:364)
at javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:302)
at javax.swing.DefaultBoundedRangeModel.setValue(DefaultBoundedRangeModel.java:168)
at javax.swing.JScrollBar.setValue(JScrollBar.java:463)
at com.apple.laf.AquaScrollBarUI$TrackListener.moveToMouse(AquaScrollBarUI.java:496)
at com.apple.laf.AquaScrollBarUI$TrackListener.mouseDraggedInTrack(AquaScrollBarUI.java:483)
at com.apple.laf.AquaScrollBarUI$TrackListener.mouseDragged(AquaScrollBarUI.java:303)
at java.awt.Component.processMouseMotionEvent(Component.java:6553)
at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3339)
at java.awt.Component.processEvent(Component.java:6274)
at java.awt.Container.processEvent(Container.java:2229)
at java.awt.Component.dispatchEventImpl(Component.java:4861)
at java.awt.Container.dispatchEventImpl(Container.java:2287)
at java.awt.Component.dispatchEvent(Component.java:4687)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4509)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
at java.awt.Container.dispatchEventImpl(Container.java:2273)
at java.awt.Window.dispatchEventImpl(Window.java:2719)
at java.awt.Component.dispatchEvent(Component.java:4687)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
at java.awt.EventQueue.access$200(EventQueue.java:103)
at java.awt.EventQueue$3.run(EventQueue.java:694)
at java.awt.EventQueue$3.run(EventQueue.java:692)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
at java.awt.EventQueue$4.run(EventQueue.java:708)
at java.awt.EventQueue$4.run(EventQueue.java:706)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

at java.lang.Thread.run(Thread.java:724)

**Comment by risserlin** [comment]
related to this is the following error:
when selecting nodes on the map, unrelated label_rectangle box were also selected, needed to "update" several times to get rid of the selection. Globally worked (except for 1 rectangle which stayed in yellow); 1 error message poped up
2015-09-28 11:23:04.143 java[43440:8694368] plugin com.google.GoogleDrive.FinderSyncAPIExtension interrupted
java.lang.NullPointerException
at org.cytoscape.ding.impl.DGraphView.getNodeView(DGraphView.java:2658)
at org.baderlab.csplugins.enrichmentmap.autoannotate.model.Cluster.updateCoordinates(Cluster.java:190)
at org.baderlab.csplugins.enrichmentmap.autoannotate.model.AnnotationSet.updateCoordinates(AnnotationSet.java:123)
at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.SelectClusterTask.deselectCluster(SelectClusterTask.java:58)
at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.SelectClusterTask.deselectCluster_nonodes(SelectClusterTask.java:156)
at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.SelectClusterTask.run(SelectClusterTask.java:172)
at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:724)
2
