### ISSUE TITLE
Periodic appearance of error "error: Update cluster label drawing cluster text label" 

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#130]

**Comment by risserlin** [comment]
moved about 3 cluster (~20node) and then clicked on update: and then got an error: Updata cluster label Drowaing cluster Text Label. I was able to close the error message and it was working well after that, the update was made despite the error
java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
at java.util.HashMap$KeyIterator.next(HashMap.java:928)
at org.cytoscape.ding.impl.cyannotator.CyAnnotator.updateNetworkAttributes(CyAnnotator.java:357)
at org.cytoscape.ding.impl.cyannotator.CyAnnotator.addAnnotation(CyAnnotator.java:275)
at org.cytoscape.ding.impl.cyannotator.annotations.AbstractAnnotation.updateAnnotationAttributes(AbstractAnnotation.java:434)
at org.cytoscape.ding.impl.cyannotator.annotations.AbstractAnnotation.update(AbstractAnnotation.java:387)
at org.cytoscape.ding.impl.cyannotator.create.TextAnnotationFactory.createAnnotation(TextAnnotationFactory.java:55)
at org.cytoscape.ding.impl.cyannotator.create.TextAnnotationFactory.createAnnotation(TextAnnotationFactory.java:41)
at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.DrawClusterLabelTask.drawTextLabel(DrawClusterLabelTask.java:83)
at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.DrawClusterLabelTask.run(DrawClusterLabelTask.java:102)
at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337)
at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:724)
