### ISSUE TITLE
changing Ellipse to rectangle error

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#131]
when you change the annotation to squares get the following stack:
Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
at java.util.HashMap$KeyIterator.next(HashMap.java:928)
at org.cytoscape.ding.impl.cyannotator.CyAnnotator.updateNetworkAttributes(CyAnnotator.java:357)
at org.cytoscape.ding.impl.cyannotator.CyAnnotator.removeAnnotation(CyAnnotator.java:280)
at org.cytoscape.ding.impl.cyannotator.annotations.AbstractAnnotation.removeAnnotation(AbstractAnnotation.java:322)
at org.baderlab.csplugins.enrichmentmap.autoannotate.model.Cluster.eraseEllipse(Cluster.java:266)
at org.baderlab.csplugins.enrichmentmap.autoannotate.view.DisplayOptionsPanel$8.itemStateChanged(DisplayOptionsPanel.java:296)
at javax.swing.AbstractButton.fireItemStateChanged(AbstractButton.java:2046)
at javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2348)
at javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:455)
at javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:272)
at javax.swing.ButtonGroup.setSelected(ButtonGroup.java:162)
at javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:254)
at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:289)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
at java.awt.Component.processMouseEvent(Component.java:6505)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
at java.awt.Component.processEvent(Component.java:6270)
at java.awt.Container.processEvent(Container.java:2229)
at java.awt.Component.dispatchEventImpl(Component.java:4861)
at java.awt.Container.dispatchEventImpl(Container.java:2287)
at java.awt.Component.dispatchEvent(Component.java:4687)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
at java.awt.Container.dispatchEventImpl(Container.java:2273)
at java.awt.Window.dispatchEventImpl(Window.java:2719)
at java.awt.Component.dispatchEvent(Component.java:4687)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
at java.awt.EventQueue.access$200(EventQueue.java:103)
at java.awt.EventQueue$3.run(EventQueue.java:694)
at java.awt.EventQueue$3.run(EventQueue.java:692)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
at java.awt.EventQueue$4.run(EventQueue.java:708)
at java.awt.EventQueue$4.run(EventQueue.java:706)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by risserlin** [comment]
Veronique, 
The change from ellipse to square still works but you get this message in the command window, right?  I think this one is fixed in cytoscape 3.3 but I will check. 
thanks,
Ruth

**Comment by veroniquevoisin** [comment]
yes, correct, it still works despite the error message
Veronique

On Thu, Oct 8, 2015 at 9:29 AM, Ruth Isserlin notifications@github.com
wrote:

> Veronique,
> The change from ellipse to square still works but you get this message in
> the command window, right? I think this one is fixed in cytoscape 3.3 but I
> will check.
> thanks,
> Ruth
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BaderLab/EnrichmentMapApp/issues/131#issuecomment-146545332
> .

## 

_Veronique Voisin, PhD_

Pathway and Network Analyses for OICR Cancer Stem Cell Research
Terrence Donnelly Centre for Cellular and Biomedical Research, University
of Toronto, 160 College Street, Toronto, M5S3E1.
_https://oicr.on.ca/oicr-programs-and-platforms/innovation-programs/cancer-stem-cells/resources
https://oicr.on.ca/oicr-programs-and-platforms/innovation-programs/cancer-stem-cells/resources_
http://baderlab.org/CSCPathwayAnalysisService
http://baderlab.org
