### ISSUE TITLE
NPE in UpdateHeatMapTask

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/EnrichmentMapApp#136]
Occasionally see this in the console:

pool-3-thread-1 ERROR [TaskMonitor.org.baderlab.csplugins.enrichmentmap.heatmap.task.UpdateHeatMapTask] - Error executing task: null
java.lang.NullPointerException
    at org.baderlab.csplugins.enrichmentmap.view.HeatMapPanel.createSortedMergedTableData(HeatMapPanel.java:1088)
    at org.baderlab.csplugins.enrichmentmap.view.HeatMapPanel.updatePanel(HeatMapPanel.java:377)
    at org.baderlab.csplugins.enrichmentmap.view.HeatMapPanel.updatePanel(HeatMapPanel.java:352)
    at org.baderlab.csplugins.enrichmentmap.heatmap.task.UpdateHeatMapTask.createNodesData(UpdateHeatMapTask.java:68)
    at org.baderlab.csplugins.enrichmentmap.heatmap.task.UpdateHeatMapTask.run(UpdateHeatMapTask.java:237)
    at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
    at org.baderlab.csplugins.enrichmentmap.actions.EnrichmentMapActionListener.handleEvent(EnrichmentMapActionListener.java:200)
    at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.cytoscape.event.internal.CyListenerAdapter.fireEvent(CyListenerAdapter.java:120)
    at org.cytoscape.event.internal.CyEventHelperImpl.flushPayloadEvents(CyEventHelperImpl.java:177)
    at org.cytoscape.event.internal.CyEventHelperImpl$1.run(CyEventHelperImpl.java:70)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by mikekucera** [comment]
Can't reproduce.

**Comment by risserlin** [comment]
I definitely see this one often but not sure what causes it.  It doesn't seem to effect anything though.  It is not consistent but I will try and see if I can reproduce it.
