### ISSUE TITLE
null pointer with post analysis

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#181]
opened post analysis panel
realized that I forgot to load ranks file so that I could use mann whitney
closed panel
loaded ranks file through heatmap
reopened post analysis panel
still won't who me mann - whitney option
click on panel reset
Mann-Whitney shows up
Change to Mann-whitney (One sided less) - even though it is still grayed out in the menu.  It allows me to select it.  
Click on Run 

Get the following stack:
java.lang.NullPointerException
	at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.mannWhitney(BuildDiseaseSignatureTask.java:572)
	at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.buildDiseaseSignature(BuildDiseaseSignatureTask.java:303)
	at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.run(BuildDiseaseSignatureTask.java:684)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:326)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by risserlin** [comment]
Work around - must load the all ranks files before initialling opening the post analysis panel in order for it to work properly.

**Comment by mikekucera** [comment]
This works in EM3
