### ISSUE TITLE
Can't create a network from command - EM beta1 

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#195]
command:
[http://localhost:1234/v1/commands/enrichmentmap/build?analysisType=gsea&gmtFile=%2FUsers%2Frisserlin%2FDropbox%20%28Bader%20Lab%29%2FCSCTeam%2FDICK%2FJD22_mir194_Gabriela%2FPathwayAnalysis%2FGSEAResults%2FOE_vs_Ctrl_unpaired_2sample.GseaPreranked.1491339132190%2Fedb%2Fgene_sets.gmt&pvalue=0.05&qvalue=0.05&similaritycutoff=0.375&ranksDataset1=%2FUsers%2Frisserlin%2FDropbox%20%28Bader%20Lab%29%2FCSCTeam%2FDICK%2FJD22_mir194_Gabriela%2FPathwayAnalysis%2FGSEAResults%2FOE_vs_Ctrl_unpaired_2sample.GseaPreranked.1491339132190%2Fedb%2FOE_rankfile_2sample.rnk&enrichmentsDataset1=%2FUsers%2Frisserlin%2FDropbox%20%28Bader%20Lab%29%2FCSCTeam%2FDICK%2FJD22_mir194_Gabriela%2FPathwayAnalysis%2FGSEAResults%2FOE_vs_Ctrl_unpaired_2sample.GseaPreranked.1491339132190%2Fedb%2Fresults.edb&expressionDataset1=%2FUsers%2Frisserlin%2FDropbox%20%28Bader%20Lab%29%2FCSCTeam%2FDICK%2FJD22_mir194_Gabriela%2FPathwayAnalysis%2FOE_mir194_exp_unpaired_expression_file.txt&coeffecients=COMBINED

Command works fine from EM 2.2.1

In the frameworks file get the following stack:
java.lang.IllegalThreadStateException: The Geneset: LOSS OF PROTEINS REQUIRED FOR INTERPHASE MICROTUBULE ORGANIZATIONÂ FROM THE CENTROSOME%REACTOME%R-HSA-380284.1 is not found in the GMT file.
	at org.baderlab.csplugins.enrichmentmap.task.InitializeGenesetsOfInterestTask.initializeSets(InitializeGenesetsOfInterestTask.java:149)
	at org.baderlab.csplugins.enrichmentmap.task.InitializeGenesetsOfInterestTask.run(InitializeGenesetsOfInterestTask.java:228)
	at org.cytoscape.command.internal.TFExecutor.execute(TFExecutor.java:90)
	at org.cytoscape.command.internal.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:175)
	at org.cytoscape.command.internal.CommandExecutorTask.run(CommandExecutorTask.java:54)
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
	at org.cytoscape.rest.internal.commands.resources.CommandResource.executeCommand(CommandResource.java:267)
	at org.cytoscape.rest.internal.commands.resources.CommandResource.handleCommand(CommandResource.java:211)
	at org.cytoscape.rest.internal.commands.resources.CommandResource.handleHTMLCommand(CommandResource.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mikekucera** [comment]
can you send me the files please

**Comment by risserlin** [comment]
This notebook and this command works fine on windows but does not work on mac.  I ran the entire notebook through on windows with no issues.  

Instead of using the gmt in the edb directory I tried using the original but got a different error (the geneset it is complaining about is in the gmt file.):

java.lang.IllegalThreadStateException: The Geneset: HALLMARK_APICAL_JUNCTION is not found in the GMT file.
	at org.baderlab.csplugins.enrichmentmap.task.InitializeGenesetsOfInterestTask.initializeSets(InitializeGenesetsOfInterestTask.java:149)
	at org.baderlab.csplugins.enrichmentmap.task.InitializeGenesetsOfInterestTask.run(InitializeGenesetsOfInterestTask.java:228)
	at org.cytoscape.command.internal.TFExecutor.execute(TFExecutor.java:90)
	at org.cytoscape.command.internal.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:175)
	at org.cytoscape.command.internal.CommandExecutorTask.run(CommandExecutorTask.java:54)
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
	at org.cytoscape.rest.internal.commands.resources.CommandResource.executeCommand(CommandResource.java:267)
	at org.cytoscape.rest.internal.commands.resources.CommandResource.handleCommand(CommandResource.java:211)
	at org.cytoscape.rest.internal.commands.resources.CommandResource.handleHTMLCommand(CommandResource.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
