### ISSUE TITLE
Hierarchical clustering crashing when there are missing expression values

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#21]

**Comment by risserlin** [comment]
clicking on particular nodes in two dataset session where the genes might not exists in both datasets produces the below error

pool-4-thread-1 ERROR [TaskMonitor.org.baderlab.csplugins.enrichmentmap.heatmap.task.UpdateHeatMapTask] - Error executing task: null
java.lang.NullPointerException
    at org.baderlab.csplugins.enrichmentmap.view.HeatMapPanel.createSortedMergedTableData(HeatMapPanel.java:848)
    at org.baderlab.csplugins.enrichmentmap.view.HeatMapPanel.updatePanel(HeatMapPanel.java:322)
    at org.baderlab.csplugins.enrichmentmap.view.HeatMapPanel.updatePanel(HeatMapPanel.java:297)
    at org.baderlab.csplugins.enrichmentmap.heatmap.task.UpdateHeatMapTask.createNodesData(UpdateHeatMapTask.java:81)
    at org.baderlab.csplugins.enrichmentmap.heatmap.task.UpdateHeatMapTask.run(UpdateHeatMapTask.java:254)
    at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
    at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:108)
    at org.baderlab.csplugins.enrichmentmap.actions.EnrichmentMapActionListener.handleEvent(EnrichmentMapActionListener.java:175)
    at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.cytoscape.event.internal.CyListenerAdapter.fireEvent(CyListenerAdapter.java:117)
    at org.cytoscape.event.internal.CyEventHelperImpl.flushPayloadEvents(CyEventHelperImpl.java:171)
    at org.cytoscape.event.internal.CyEventHelperImpl$1.run(CyEventHelperImpl.java:68)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
