### ISSUE TITLE
Files created in Cytoscape 3 bingo not working in EM 2.0

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#23]
Bingo files created in 2.8 work but not bingo files that were created in 3.0

java.lang.ArrayIndexOutOfBoundsException: 1
        at org.baderlab.csplugins.enrichmentmap.parsers.EnrichmentResultFileRead
erTask.parseGenericFile(EnrichmentResultFileReaderTask.java:359)
        at org.baderlab.csplugins.enrichmentmap.parsers.EnrichmentResultFileRead
erTask.readFile(EnrichmentResultFileReaderTask.java:219)
        at org.baderlab.csplugins.enrichmentmap.parsers.EnrichmentResultFileRead
erTask.parse(EnrichmentResultFileReaderTask.java:143)
        at org.baderlab.csplugins.enrichmentmap.parsers.EnrichmentResultFileRead
erTask.run(EnrichmentResultFileReaderTask.java:973)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.inne
rRun(JDialogTaskManager.java:337)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(
JDialogTaskManager.java:350)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:44
1)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExec
utor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:908)
        at java.lang.Thread.run(Thread.java:662)

**Comment by risserlin** [comment]
fixed in 444942b40f78fec44cfb4f87bbc775958cdf117e
