### ISSUE TITLE
Heatmap crashing sometimes when set to hierarchical clustering

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#31]

**Comment by risserlin** [comment]
java.lang.NullPointerException
    at org.baderlab.csplugins.enrichmentmap.view.HeatMapPanel.createSortedTableData(HeatMapPanel.java:738)
    at org.baderlab.csplugins.enrichmentmap.view.HeatMapPanel.updatePanel(HeatMapPanel.java:339)
    at org.baderlab.csplugins.enrichmentmap.view.HeatMapPanel.updatePanel(HeatMapPanel.java:300)
    at org.baderlab.csplugins.enrichmentmap.heatmap.task.UpdateHeatMapTask.createNodesData(UpdateHeatMapTask.java:80)
    at org.baderlab.csplugins.enrichmentmap.heatmap.task.UpdateHeatMapTask.run(UpdateHeatMapTask.java:252)
    at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
    at org.baderlab.csplugins.enrichmentmap.actions.EnrichmentMapActionListener.handleEvent(EnrichmentMapActionListener.java:187)
    at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.cytoscape.event.internal.CyListenerAdapter.fireEvent(CyListenerAdapter.java:117)
    at org.cytoscape.event.internal.CyEventHelperImpl.flushPayloadEvents(CyEventHelperImpl.java:171)
    at org.cytoscape.event.internal.CyEventHelperImpl$1.run(CyEventHelperImpl.java:68)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

**Comment by risserlin** [comment]
fixed in aae5806a0991fc80a7e327bb467621c83faf3cfc
