### ISSUE TITLE
Unable to create Enrichment Map: Internal Server Error - Failed: empty String 

### ISSUE THREAD

**Issue by mjrich79** [BaderLab/EnrichmentMapApp#381]
I am trying to build a map using GSEA and the plugin. I am able to get through the workflow fine up until I want to create a map. I am getting the same error whether I try and launch from EnrichmentMap in Cytoscape or from GSEA. 

some additional info in the window. 

`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.gsea_msigdb.gsea/edu.mit.broad.cytoscape.view.EnrichmentMapParameterPanel.selectJaccardOrOverlapActionPerformed(EnrichmentMapParameterPanel.java:462)
	at org.gsea_msigdb.gsea/edu.mit.broad.cytoscape.view.EnrichmentMapParameterPanel.access$100(EnrichmentMapParameterPanel.java:54)
	at org.gsea_msigdb.gsea/edu.mit.broad.cytoscape.view.EnrichmentMapParameterPanel$2.actionPerformed(EnrichmentMapParameterPanel.java:225)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at looks@2.0.4/com.jgoodies.looks.plastic.ActiveBasicButtonListener.mouseReleased(ActiveBasicButtonListener.java:69)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by risserlin** [comment]
What version of cytoscape and enrichment map are you using?  Also, are you on Windows, Mac or linux?  
It looks like it might not be able to even open the EM panel.  Are you able to enter all your GSEA results files into the interface but when you push on build it fails with the above error message?

**Comment by mikekucera** [comment]
The stack trace is from GSEA desktop not from EnrichmentMap.
