### ISSUE TITLE
Missing argument in the build-table command to import qvalues. 

### ISSUE THREAD

**Issue by scaramonche** [BaderLab/EnrichmentMapApp#416]
Hi Mike, 

Currently, I can only provide a column for the pvalues as an argument in the build-table command of EM ("pvalueColumn"), but I would like to provide a column for the qvalues ("qvalueColumn"). 

I saw in the source code that for the import from the stringApp, the FDR values (qvalues) are taken. This is exactly the functionality I would like to have in the command and I suspect it is just not exposed as an argument yet. 

In addition, we actually have both pvalues and FDR values in the stringApp enrichment, although the pvalues are currently not saved in the right table. I will change that and would like to provide EM with both the pvalues and the FDR values. Then, you could also get both of them when you do the EM from stringApp enrichment.

Thanks, 
Nadya

**Comment by mikekucera** [comment]
The string enrichment table has a column 'network.SUID'. It looks like all the enrichments for all the string networks are in that one table, correct? If that's the case then the 'build-table' command probably also needs a way to filter the rows so that it just uses rows for one network at a time. Do you agree?

**Comment by scaramonche** [comment]
I am not entirely sure what you mean. For each network, we create its own enrichment table and we save the network SUID to have it. I think we use it to can connect the enrichment table back to the network when the session is reloaded, but I would need to double-check that. So the enrichment results for different networks are not all saved in the same table, however the tables have the same name "STRING Enrichment: All". Then, we use the table SUID, which is unique for each enrichment run for each network, to call the build-table command.

**Comment by mikekucera** [comment]
Thanks for clarifying. It shouldn't be necessary to filter the table.

**Comment by scaramonche** [comment]
Hey, I was just testing that. If I only use the qvalueColumn parameter but not the pvalueColumn one, I get an error. Is this on purpose, such that either only pvalues or both can be given as input or a bug?

`java.lang.IllegalArgumentException: None of the gene sets have passed the filter. Try relaxing the gene set filter parameters.
	at org.baderlab.csplugins.enrichmentmap.task.InitializeGenesetsOfInterestTask.initializeSets(InitializeGenesetsOfInterestTask.java:182) ~[?:?]
	at org.baderlab.csplugins.enrichmentmap.task.InitializeGenesetsOfInterestTask.run(InitializeGenesetsOfInterestTask.java:246) ~[?:?]
	at org.cytoscape.command.internal.TFExecutor.execute(TFExecutor.java:89) ~[?:?]
	at org.cytoscape.command.internal.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:175) ~[?:?]
	at org.cytoscape.command.internal.CommandExecutorTask.run(CommandExecutorTask.java:54) ~[?:?]
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337) ~[93:org.cytoscape.work-swing-impl:3.8.0]
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:352) [93:org.cytoscape.work-swing-impl:3.8.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by scaramonche** [comment]
With both columns it works! And the pvalue column in the STRING enrichment table is called "p-value" in case you want to include it as well. It should be available once we release the current version.
