### ISSUE TITLE
Post_Analysis / defect / source node is not a member of this network

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#48]
It is not possible to change the parameters settings to rerun the overlap of the signatures twice on the same session. A "source node is not a member of this network" error appear. 

What I'm trying to do is to try different thresholds for example, I try number of common of genes = 1 and then realize that there are too  many overlaps and then I try hypergeometric = 0.05, etc,, To do  in Cytoscape 2.8 , I delete the signature nodes ( triangle) and related edges and rerun the post-analysis. Here the error (source node is not a member of this network) appears when I hit the "run" button twice.

ERROR LOG AND ENRICHMENT MAP VERSION BELOW:
Cytoscape 3.1.1 EnrichmentMap 2.0.1 build 478  java6

java.lang.IllegalArgumentException: source node is not a member of this network
    at org.cytoscape.model.internal.SimpleNetwork.addEdgeInternal(SimpleNetwork.java:265)
    at org.cytoscape.model.internal.CyRootNetworkImpl.addEdge(CyRootNetworkImpl.java:254)
    at org.cytoscape.model.internal.CySubNetworkImpl.addEdge(CySubNetworkImpl.java:149)
    at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.buildDiseaseSignature(BuildDiseaseSignatureTask.java:444)
    at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.run(BuildDiseaseSignatureTask.java:707)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)

**Comment by risserlin** [comment]
fixed in e5cd791ec72340d51e387bd052f414ec05496814
