### ISSUE TITLE
Can't save/restore Enrichment map with annotations on Windows

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#50]
java.lang.NullPointerException
        at org.baderlab.csplugins.enrichmentmap.actions.EnrichmentMapSessionActi
on.handleEvent(EnrichmentMapSessionAction.java:81)
        at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.cytoscape.event.internal.CyListenerAdapter.fireEvent(CyListenerAd
apter.java:120)
        at org.cytoscape.event.internal.CyEventHelperImpl.fireEvent(CyEventHelpe
rImpl.java:84)
        at org.cytoscape.session.internal.CySessionManagerImpl.setCurrentSession
(CySessionManagerImpl.java:268)
        at org.cytoscape.task.internal.session.OpenSessionTask$OpenSessionWithou
tWarningTask.changeCurrentSession(OpenSessionTask.java:184)
        at org.cytoscape.task.internal.session.OpenSessionTask$OpenSessionWithou
tWarningTask.run(OpenSessionTask.java:160)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.inne
rRun(JDialogTaskManager.java:337)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(
JDialogTaskManager.java:350)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:47
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by risserlin** [comment]
fixed
