### ISSUE TITLE
AutoAnnotate error log

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#52]
Hi Ruth,
here is the log from yesterday's trial:
###### 

tried to remove the annotations: Annotation Sets: "REMOVE"
###### 

java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
    at java.util.HashMap$KeyIterator.next(HashMap.java:928)
    at org.cytoscape.ding.impl.cyannotator.CyAnnotator.updateNetworkAttributes(CyAnnotator.java:357)
    at org.cytoscape.ding.impl.cyannotator.CyAnnotator.removeAnnotation(CyAnnotator.java:280)
    at org.cytoscape.ding.impl.cyannotator.annotations.AbstractAnnotation.removeAnnotation(AbstractAnnotation.java:320)
    at org.baderlab.csplugins.enrichmentmap.autoannotate.model.Cluster.eraseText(Cluster.java:260)
    at org.baderlab.csplugins.enrichmentmap.autoannotate.model.Cluster.erase(Cluster.java:254)
    at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.DeleteClusterTask.destroyCluster(DeleteClusterTask.java:97)
    at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.DeleteClusterTask.run(DeleteClusterTask.java:55)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

==> the new annotations were removed but the old annotations from the stored session "re-appeared".
###### 

moving some nodes and/or selecting multiple nodes
###### 

wordcloud select cloudName="MCL Cluster Annotation Set Cloud 40" updateNodeSelection=false
wordcloud select cloudName="MCL Cluster Annotation Set Cloud 37" updateNodeSelection=false
wordcloud select cloudName="MCL Cluster Annotation Set Cloud 120" updateNodeSelection=false
wordcloud select cloudName="MCL Cluster Annotation Set Cloud 22" updateNodeSelection=false
wordcloud select cloudName="MCL Cluster Annotation Set Cloud 37" updateNodeSelection=false
wordcloud select cloudName="MCL Cluster Annotation Set Cloud 22" updateNodeSelection=false
wordcloud select cloudName="MCL Cluster Annotation Set Cloud 62" updateNodeSelection=false
wordcloud select cloudName="MCL Cluster Annotation Set Cloud 96" updateNodeSelection=false
wordcloud select cloudName="MCL Cluster Annotation Set Cloud 23" updateNodeSelection=false
Thu Nov 27 11:16:47 MacPro9.local java[9445] <Error>: kCGErrorInvalidOperation: Cannot merge groups (yet) for wid 4b65, otherwid 4933
Thu Nov 27 11:16:47 MacPro9.local java[9445] <Error>: kCGErrorInvalidOperation: Cannot merge groups (yet) for wid 4b67, otherwid 4933
Thu Nov 27 11:16:48 MacPro9.local java[9445] <Error>: kCGErrorInvalidOperation: Cannot merge groups (yet) for wid 4b69, otherwid 4933
Thu Nov 27 11:16:48 MacPro9.local java[9445] <Error>: kCGErrorInvalidOperation: Cannot merge groups (yet) for wid 4b6b, otherwid 4933

 ==> "Cytoscape task" window is running and running: I don't know what Cytoscape is trying to do ==> force quit Cytoscape at that point
###### 

selecting nodes from 2 different clusters: --> "Drawing Ellipse/Box around cluster" error window 
###### 

 java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
    at java.util.HashMap$KeyIterator.next(HashMap.java:928)
    at org.cytoscape.ding.impl.cyannotator.CyAnnotator.updateNetworkAttributes(CyAnnotator.java:357)
    at org.cytoscape.ding.impl.cyannotator.CyAnnotator.addAnnotation(CyAnnotator.java:275)
    at org.cytoscape.ding.impl.cyannotator.annotations.AbstractAnnotation.updateAnnotationAttributes(AbstractAnnotation.java:432)
    at org.cytoscape.ding.impl.cyannotator.annotations.AbstractAnnotation.update(AbstractAnnotation.java:385)
    at org.cytoscape.ding.impl.cyannotator.create.ShapeAnnotationFactory.createAnnotation(ShapeAnnotationFactory.java:54)
    at org.cytoscape.ding.impl.cyannotator.create.ShapeAnnotationFactory.createAnnotation(ShapeAnnotationFactory.java:41)
    at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.DrawClusterEllipseTask.drawEllipse(DrawClusterEllipseTask.java:86)
    at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.DrawClusterEllipseTask.run(DrawClusterEllipseTask.java:122)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

==> just close the error window: the ellipse around the node cluster that has been selected is not drawn but cytoscape is not crashing

Thanks,
Veronique

**Comment by risserlin** [comment]
kCGErrorInvalidOperation: Cannot merge groups (yet) for wid 4b65, otherwid 4933 - related to our hacked version of Java 7 + snow leopard.  (should be fixed in OS upgrade.)

Got rid of print statements in the console. (b2c03d125c4a880cae5299404478d0e8490ec5a0)
Fixed concurrency issues in e1f0fae80ce946b429477548f1aba2d4a83bf6ec
