### ISSUE TITLE
index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/EnrichmentMapApp#524]
If there's a bad line in an enrichment file this happens...

<img width="666" alt="Screenshot 2023-07-19 at 11 10 25 AM" src="https://github.com/BaderLab/EnrichmentMapApp/assets/5350528/575f8f4a-252f-4a09-a63d-a083b9eacc1e">

If its just a blank line then it should be ignored.
If its actually a badly formatted line then give the user a better error message!

```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.baderlab.csplugins.enrichmentmap.parsers.ParseGenericEnrichmentResults.parse(ParseGenericEnrichmentResults.java:79)
	at org.baderlab.csplugins.enrichmentmap.parsers.ParseGenericEnrichmentResults.run(ParseGenericEnrichmentResults.java:34)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:352)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mikekucera** [comment]
The error message now reports the file and line number where the parsing error occurred.
Also blank lines are skipped so if the file ends with a blank line that's now ignored.

<img width="554" alt="Screenshot 2023-07-25 at 5 17 00 PM" src="https://github.com/BaderLab/EnrichmentMapApp/assets/5350528/734817c4-c401-4458-a832-1cb691166fa0">
