### ISSUE TITLE
running post analysis on second network in session gives the following stack

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#79]
java.lang.IllegalArgumentException: column: 'EM1_Formatted_name' does not yet exist.
    at org.cytoscape.model.internal.CyTableImpl.setX(CyTableImpl.java:653)
    at org.cytoscape.model.internal.CyTableImpl.access$100(CyTableImpl.java:64)
    at org.cytoscape.model.internal.CyTableImpl$InternalRow.set(CyTableImpl.java:1193)
    at org.cytoscape.model.internal.AbstractTableFacade$RowFacade.set(AbstractTableFacade.java:235)
    at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.createHubNode(BuildDiseaseSignatureTask.java:430)
    at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.buildDiseaseSignature(BuildDiseaseSignatureTask.java:335)
    at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.run(BuildDiseaseSignatureTask.java:758)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by mikekucera** [comment]
Are you running post-analysis on a network that was created by enrichment map? The missing column is supposed to be created by the CreateEnrichmentMapNetworkTask. It would be a good idea in general to check for all the required columns before running the post analysis task.

**Comment by risserlin** [comment]
Yes.  I am running post analysis on a network created by the latest version of enrichment map (not a restored session).

To recreate:
Create EM
Create second EM in the same session (you can use the exact same parameters).
Go to the first network and run a post analysis.
Then go to the second network and run a post analysis.

Get the following error (with the above stack in console):
![screen shot 2015-04-27 at 9 54 43 am](https://cloud.githubusercontent.com/assets/3842763/7348928/853dd698-ecc3-11e4-97c8-69c47478b24c.png)
