### ISSUE TITLE
if annotation label or attribute used to create it is empty EM returns null pointer

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#91]
java.lang.NullPointerException
        at org.baderlab.csplugins.enrichmentmap.autoannotate.model.Cluster.makeL
abel(Cluster.java:374)
        at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.Update
ClusterLabelTask.updateClusterLabel(UpdateClusterLabelTask.java:67)
        at org.baderlab.csplugins.enrichmentmap.autoannotate.task.cluster.Update
ClusterLabelTask.run(UpdateClusterLabelTask.java:91)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.inne
rRun(JDialogTaskManager.java:337)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(
JDialogTaskManager.java:350)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:47
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by risserlin** [comment]
fixed in 10b15ef347356a6a205ede2a0ae27496d7e9ada5
