### ISSUE TITLE
Null pointer when removing an annotation set

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#93]
(might be related to issue #91

Create a annotation set (with a column that contains a few blank values)

Click on remove annotation
Get the following error:
java.lang.NullPointerException
        at org.baderlab.csplugins.enrichmentmap.autoannotate.task.RemoveAnnotati
onTask.removeAction(RemoveAnnotationTask.java:41)
        at org.baderlab.csplugins.enrichmentmap.autoannotate.task.RemoveAnnotati
onTask.run(RemoveAnnotationTask.java:64)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.inne
rRun(JDialogTaskManager.java:321)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(
JDialogTaskManager.java:350)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:47
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by risserlin** [comment]
fixed in 167c41938118910086f3971ef627605d9a81be88
