### ISSUE TITLE
Restored session with deleted annotation returns error

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#94]
When auto annotate is removing an annotation it is not deleting the unassigned tables that it has created

Create session with annotations
Delete annotations
Save session
reload session
Try to annotate network

Get the following error:
java.lang.IllegalArgumentException: Cloud name already in use: mclCluster Column
 Annotation Set Cloud 1
        at org.baderlab.wordcloud.internal.model.NetworkParameters.createCloud(N
etworkParameters.java:121)
        at org.baderlab.wordcloud.internal.model.CloudBuilder.build(CloudBuilder
.java:45)
        at org.baderlab.wordcloud.internal.command.CreateWordCloudCommandHandler
Task.run(CreateWordCloudCommandHandlerTask.java:122)
        at org.cytoscape.command.internal.TFExecutor.execute(TFExecutor.java:90)

```
    at org.cytoscape.command.internal.CommandExecutorImpl.executeCommand(Com
```

mandExecutorImpl.java:180)
        at org.cytoscape.command.internal.CommandExecutorImpl.handleCommand(Comm
andExecutorImpl.java:221)
        at org.cytoscape.command.internal.CommandExecutorImpl.executeList(Comman
dExecutorImpl.java:158)
        at org.cytoscape.command.internal.CommandStringsExecutorTask.run(Command
StringsExecutorTask.java:50)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.inne
rRun(JDialogTaskManager.java:321)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(
JDialogTaskManager.java:350)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:47
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by risserlin** [comment]
Workaround - 
In Table Panel to to Unassigned Tables tab
Delete the tables corresponding to deleted annotations.

**Comment by risserlin** [comment]
fixed with other deletion fixes.  restored session no longer has unassigned table.
